os:
  - linux
  - osx
language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
matrix:
  allow_failures:
  - php: hhvm
  - os: osx
before_script:
  - composer clearcache
  - composer install --dev
script:
  - "./vendor/bin/phpunit"
notifications:
  email:
    recipients:
    - david@verholen.com
    on_success: never
    on_failure: always
